sudo: required

language: go

go:
  - 1.9.x

env:
  global:
    - HELM_URL=https://storage.googleapis.com/kubernetes-helm
    - HELM_TAR=helm-v2.4.1-linux-amd64.tar.gz

install:
  - wget -q ${HELM_URL}/${HELM_TAR}
  - tar xzfv ${HELM_TAR}
  - PATH=`pwd`/linux-amd64/:$PATH
  - helm init --client-only

services:
  - docker

before_script:
- bash contrib/set_travis_experimental_mode.sh
- curl -sSL get.docker.com | sudo -E sh

script:
  - make build
  - >
     for chart in `ls ./chart`; do
      helm lint ./chart/${chart}
      if [ $? != 0 ]; then
       travis_terminate 1
      fi
     done

after_success:
    - if [ -z $DOCKER_NS ] ; then
        export DOCKER_NS=openfaas;
        fi

    - if [ ! -z "$TRAVIS_TAG" ] ; then 
        docker tag $DOCKER_NS/faas-netes:latest $DOCKER_NS/faas-netes:$TRAVIS_TAG;
        echo $DOCKER_PASSWORD | docker login -u=$DOCKER_USERNAME --password-stdin;
        docker push $DOCKER_NS/faas-netes:$TRAVIS_TAG;

        docker tag $DOCKER_NS/faas-netes:latest quay.io/$DOCKER_NS/faas-netes:$TRAVIS_TAG;
        echo $QUAY_PASSWORD | docker login -u=$QUAY_USERNAME --password-stdin quay.io;
        docker push quay.io/$DOCKER_NS/faas-netes:$TRAVIS_TAG;

        fi