apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: alertmanager
  namespace: openfaas
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      serviceAccountName: faas-controller
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.15.0
        imagePullPolicy: Always
        command: 
          - "alertmanager"
          - "--config.file=/alertmanager.yml"
          - "--storage.path=/alertmanager"
        ports:
        - containerPort: 9003
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 25Mi
          limits:
            cpu: 100m
            memory: 50Mi
        volumeMounts:
        - mountPath: /alertmanager.yml
          name: alertmanager-config
          subPath: alertmanager.yml
      volumes:
        - name: alertmanager-config
          configMap:
            name: alertmanager-config
            items:
              - key: alertmanager.yml
                path: alertmanager.yml
                mode: 0644
