apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: openfaas
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30000 
  selector:
    app: grafana

